version: '3'
services:
    sequelize:
        build: ./
        command: sh -c "npm install && npm run migrate:up && npm start"
        volumes:
            - ./sequelize:usr/src/app
        ports:
            - 3000:3002

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sequelizedb
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
volumes:
    db_data:
